# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: self_debug/proto/ast_parser.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!self_debug/proto/ast_parser.proto\x12\x03\x61ws\"8\n\rJavaAstParser\x12\x10\n\x08root_dir\x18\x01 \x01(\t\x12\x15\n\x08mvn_path\x18\x02 \x01(\t:\x03mvn\"\x88\x01\n\tAstParser\x12-\n\x0fjava_ast_parser\x18\x02 \x01(\x0b\x32\x12.aws.JavaAstParserH\x00\x12\x18\n\nenable_ast\x18\x03 \x01(\x08:\x04true\x12$\n\x16\x65nable_package_upgrade\x18\x04 \x01(\x08:\x04trueB\x0c\n\nast_parser')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'self_debug.proto.ast_parser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JAVAASTPARSER']._serialized_start=42
  _globals['_JAVAASTPARSER']._serialized_end=98
  _globals['_ASTPARSER']._serialized_start=101
  _globals['_ASTPARSER']._serialized_end=237
# @@protoc_insertion_point(module_scope)
