# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: self_debug/proto/builder.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eself_debug/proto/builder.proto\x12\x03\x61ws\"\x93\x02\n\x0cMavenBuilder\x12\x10\n\x08root_dir\x18\x01 \x01(\t\x12\x10\n\x08jdk_path\x18\x02 \x01(\t\x12\x36\n\rbuild_command\x18\x03 \x01(\t:\x1f\x63\x64 {root_dir}; mvn clean verify\x12\x31\n\x1a\x62uild_command_sanity_check\x18\x04 \x01(\t:\rmvn --version\x12%\n\x17require_maven_installed\x18\x05 \x01(\x08:\x04true\x12\x36\n(require_test_class_and_method_invariance\x18\x06 \x01(\x08:\x04true\x12\x15\n\rsource_branch\x18\x07 \x01(\t\"\x88\x03\n\x07\x42uilder\x12*\n\rmaven_builder\x18\x02 \x01(\x0b\x32\x11.aws.MavenBuilderH\x00\x12\x17\n\x0f\x65nable_feedback\x18\x03 \x01(\x08\x12\x64\n\x19\x62uild_error_change_option\x18\x04 \x01(\x0e\x32#.aws.Builder.BuildErrorChangeOption:\x1c\x45RRORS_DIFFERENT_FROM_BEFORE\x12\x19\n\x11\x65nable_reflection\x18\t \x01(\x08\x12\x19\n\x11max_context_files\x18\x0b \x01(\x05\"\x90\x01\n\x16\x42uildErrorChangeOption\x12\x0b\n\x07UNKNOWN\x10\x00\x12 \n\x1c\x45RRORS_DIFFERENT_FROM_BEFORE\x10\x01\x12\x15\n\x11\x45RRORS_NOT_A_SWAP\x10\x04\x12\x19\n\x15\x45RRORS_NON_INCREASING\x10\x02\x12\x15\n\x11\x45RRORS_DECREASING\x10\x03\x42\t\n\x07\x62uilder')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'self_debug.proto.builder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAVENBUILDER']._serialized_start=40
  _globals['_MAVENBUILDER']._serialized_end=315
  _globals['_BUILDER']._serialized_start=318
  _globals['_BUILDER']._serialized_end=710
  _globals['_BUILDER_BUILDERRORCHANGEOPTION']._serialized_start=555
  _globals['_BUILDER_BUILDERRORCHANGEOPTION']._serialized_end=699
# @@protoc_insertion_point(module_scope)
