# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: self_debug/proto/cloudwatch.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!self_debug/proto/cloudwatch.proto\x12\x03\x61ws\"\xbf\x01\n\x10\x43loudWatchMetric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\tint_value\x18\x02 \x01(\x05H\x00\x12\x15\n\x0b\x66loat_value\x18\x03 \x01(\x02H\x00\x12\x0c\n\x04unit\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\x12%\n\x08timezone\x18\x06 \x01(\t:\x13\x41merica/Los_Angeles\x12\x0f\n\x07publish\x18\x07 \x01(\x08\x12\x0f\n\x07\x63omment\x18\x08 \x01(\tB\x07\n\x05value\"\xd1\x02\n\x11\x43loudWatchMetrics\x12\x0f\n\x07publish\x18\x01 \x01(\x08\x12 \n\tnamespace\x18\x02 \x01(\t:\rEMRServerless\x12:\n\rcw_dimensions\x18\x03 \x01(\x0b\x32#.aws.CloudWatchMetrics.CwDimensions\x12&\n\x07metrics\x18\x04 \x03(\x0b\x32\x15.aws.CloudWatchMetric\x1a\xa4\x01\n\x0c\x43wDimensions\x12L\n\rdimension_map\x18\x01 \x03(\x0b\x32\x35.aws.CloudWatchMetrics.CwDimensions.DimensionMapEntry\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x1a\x33\n\x11\x44imensionMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"=\n\x06\x43onfig\x12\x33\n\x13\x63loud_watch_metrics\x18\x01 \x01(\x0b\x32\x16.aws.CloudWatchMetrics')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'self_debug.proto.cloudwatch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLOUDWATCHMETRICS_CWDIMENSIONS_DIMENSIONMAPENTRY']._loaded_options = None
  _globals['_CLOUDWATCHMETRICS_CWDIMENSIONS_DIMENSIONMAPENTRY']._serialized_options = b'8\001'
  _globals['_CLOUDWATCHMETRIC']._serialized_start=43
  _globals['_CLOUDWATCHMETRIC']._serialized_end=234
  _globals['_CLOUDWATCHMETRICS']._serialized_start=237
  _globals['_CLOUDWATCHMETRICS']._serialized_end=574
  _globals['_CLOUDWATCHMETRICS_CWDIMENSIONS']._serialized_start=410
  _globals['_CLOUDWATCHMETRICS_CWDIMENSIONS']._serialized_end=574
  _globals['_CLOUDWATCHMETRICS_CWDIMENSIONS_DIMENSIONMAPENTRY']._serialized_start=523
  _globals['_CLOUDWATCHMETRICS_CWDIMENSIONS_DIMENSIONMAPENTRY']._serialized_end=574
  _globals['_CONFIG']._serialized_start=576
  _globals['_CONFIG']._serialized_end=637
# @@protoc_insertion_point(module_scope)
