# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: self_debug/proto/llm_parser.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!self_debug/proto/llm_parser.proto\x12\x03\x61ws\"\xdc\x01\n\x0eRegexLlmParser\x12\x12\n\x04\x66ind\x18\x01 \x01(\t:\x04\x46ind\x12\x18\n\x07replace\x18\x02 \x01(\t:\x07Replace\x12&\n\x0b\x62lock_start\x18\x03 \x01(\t:\x11\\[{regex} Start\\]\x12\"\n\tblock_end\x18\x04 \x01(\t:\x0f\\[{regex} End\\]\x12\x13\n\x05strip\x18\x05 \x01(\x08:\x04true\x12\x14\n\x06rstrip\x18\x06 \x01(\x08:\x04true\x12%\n\x17require_same_num_blocks\x18\x07 \x01(\x08:\x04true\"e\n\tLlmParser\x12/\n\x10regex_llm_parser\x18\x01 \x01(\x0b\x32\x13.aws.RegexLlmParserH\x00\x12\x1d\n\x0f\x65nable_feedback\x18\x02 \x01(\x08:\x04trueB\x08\n\x06parser\"\x94\x01\n\x15RegexLlmParserByGroup\x12\x15\n\x05group\x18\x01 \x01(\t:\x06\x43hange\x12\x33\n\x11regex_group_start\x18\x02 \x01(\t:\x18\\[{regex} Start [^\\]]+\\]\x12/\n\x0fregex_group_end\x18\x03 \x01(\t:\x16\\[{regex} End [^\\]]+\\]\"\xcd\x01\n\x10LlmParserByGroup\x12?\n\x19regex_llm_parser_by_group\x18\x01 \x01(\x0b\x32\x1a.aws.RegexLlmParserByGroupH\x00\x12$\n\x0c\x62lock_parser\x18\x02 \x01(\x0b\x32\x0e.aws.LlmParser\x12\x1d\n\x0f\x65nable_feedback\x18\x03 \x01(\x08:\x04true\x12)\n\x1bmaybe_rewrite_group_as_file\x18\x04 \x01(\x08:\x04trueB\x08\n\x06parser')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'self_debug.proto.llm_parser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGEXLLMPARSER']._serialized_start=43
  _globals['_REGEXLLMPARSER']._serialized_end=263
  _globals['_LLMPARSER']._serialized_start=265
  _globals['_LLMPARSER']._serialized_end=366
  _globals['_REGEXLLMPARSERBYGROUP']._serialized_start=369
  _globals['_REGEXLLMPARSERBYGROUP']._serialized_end=517
  _globals['_LLMPARSERBYGROUP']._serialized_start=520
  _globals['_LLMPARSERBYGROUP']._serialized_end=725
# @@protoc_insertion_point(module_scope)
