# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: self_debug/proto/metrics.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eself_debug/proto/metrics.proto\x12\x03\x61ws\"v\n\x0bRepoMetrics\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x1a\n\x12repo_size_in_bytes\x18\x02 \x01(\x02\x12\x14\n\x0cnum_projects\x18\x03 \x01(\x05\x12\x11\n\tnum_files\x18\x04 \x01(\x05\x12\x15\n\rfile_suffixes\x18\x05 \x03(\t\"F\n\x0cStateMetrics\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nnum_errors\x18\x02 \x01(\x05\x12\x11\n\titeration\x18\x03 \x01(\x05\"\xc8\x01\n\x0f\x45\x66\x66icacyMetrics\x12 \n\x05state\x18\x01 \x01(\x0b\x32\x11.aws.StateMetrics\x12\x16\n\x0emax_iterations\x18\x03 \x01(\x05\x12\x12\n\niterations\x18\x02 \x01(\x05\x12\x18\n\x10h_min_iterations\x18\x04 \x01(\x05\x12\x18\n\x10h_max_iterations\x18\x05 \x01(\x05\x12\x1b\n\x13h_num_errors_factor\x18\x06 \x01(\x02\x12\x16\n\x0e\x64\x65precated_api\x18\x07 \x01(\x05\"!\n\x0eLatencyMetrics\x12\x0f\n\x07seconds\x18\x01 \x01(\x02\"\x90\x01\n\nLlmMetrics\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x02 \x01(\x08\x12\x14\n\x0cinput_tokens\x18\x03 \x01(\x05\x12\x15\n\routput_tokens\x18\x04 \x01(\x05\x12\x0c\n\x04\x63ost\x18\x05 \x01(\x02\x12$\n\x07latency\x18\x06 \x01(\x0b\x32\x13.aws.LatencyMetrics\"\xbf\x02\n\x07Metrics\x12&\n\x0crepo_metrics\x18\x01 \x01(\x0b\x32\x10.aws.RepoMetrics\x12\x30\n\x15initial_state_metrics\x18\x02 \x01(\x0b\x32\x11.aws.StateMetrics\x12\x35\n\x1aintermediate_state_metrics\x18\x07 \x03(\x0b\x32\x11.aws.StateMetrics\x12\x31\n\x13\x66inal_state_metrics\x18\x03 \x01(\x0b\x32\x14.aws.EfficacyMetrics\x12$\n\x07latency\x18\x04 \x01(\x0b\x32\x13.aws.LatencyMetrics\x12$\n\x0bllm_summary\x18\x05 \x01(\x0b\x32\x0f.aws.LlmMetrics\x12$\n\x0bllm_metrics\x18\x06 \x03(\x0b\x32\x0f.aws.LlmMetrics')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'self_debug.proto.metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPOMETRICS']._serialized_start=39
  _globals['_REPOMETRICS']._serialized_end=157
  _globals['_STATEMETRICS']._serialized_start=159
  _globals['_STATEMETRICS']._serialized_end=229
  _globals['_EFFICACYMETRICS']._serialized_start=232
  _globals['_EFFICACYMETRICS']._serialized_end=432
  _globals['_LATENCYMETRICS']._serialized_start=434
  _globals['_LATENCYMETRICS']._serialized_end=467
  _globals['_LLMMETRICS']._serialized_start=470
  _globals['_LLMMETRICS']._serialized_end=614
  _globals['_METRICS']._serialized_start=617
  _globals['_METRICS']._serialized_end=936
# @@protoc_insertion_point(module_scope)
