# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: self_debug/proto/model.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cself_debug/proto/model.proto\x12\x03\x61ws\"\xb7\x04\n\x05Model\x12\x12\n\x08model_id\x18\x01 \x01(\tH\x00\x12.\n\x0cmodel_option\x18\x02 \x01(\x0e\x32\x16.aws.Model.ModelOptionH\x00\x12\r\n\x05top_k\x18\x03 \x01(\x05\x12\r\n\x05top_p\x18\x04 \x01(\x02\x12\x13\n\x0btemperature\x18\x05 \x01(\x02\x12\x18\n\nmax_tokens\x18\x06 \x01(\x05:\x04\x31\x30\x32\x34\x12-\n\x11\x61nthropic_version\x18\x07 \x01(\t:\x12\x62\x65\x64rock-2023-05-31\"\xe4\x02\n\x0bModelOption\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x10\n\x0c\x41WS_CLAUDE_2\x10\x01\x12\x12\n\x0e\x41WS_CLAUDE_2D1\x10\x02\x12\x10\n\x0c\x41WS_CLAUDE_3\x10\x03\x12\x16\n\x12\x41WS_CLAUDE_3_HAIKU\x10\x04\x12\x15\n\x11\x41WS_CLAUDE_3_OPUS\x10\x05\x12\x17\n\x13\x41WS_CLAUDE_3_SONNET\x10\x06\x12\x18\n\x14\x41WS_CLAUDE_35_SONNET\x10\x07\x12\x1b\n\x17\x41WS_CLAUDE_35_V2_SONNET\x10\x08\x12\x10\n\x0c\x41WS_NOVA_PRO\x10\t\x12\x14\n\x10\x41WS_LLAMA_31_70B\x10\n\x12\x17\n\x13\x41WS_MISTRAL_LARGE_2\x10\x0b\x12\x17\n\x13\x41WS_CLAUDE_35_HAIKU\x10\x0c\x12\x17\n\x13US_AWS_LLAMA_31_70B\x10\r\x12\x1e\n\x1aUS_AWS_CLAUDE_35_V2_SONNET\x10\x0e\x42\x07\n\x05model')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'self_debug.proto.model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODEL']._serialized_start=38
  _globals['_MODEL']._serialized_end=605
  _globals['_MODEL_MODELOPTION']._serialized_start=240
  _globals['_MODEL_MODELOPTION']._serialized_end=596
# @@protoc_insertion_point(module_scope)
