set -x

python ./batch/test_configs.py
python ./common/test_configs.py
python ./common/test_file_utils.py
python ./common/test_filesystem_writer_factory.py
python ./common/test_git_repo.py
python ./common/test_github.py
python ./common/test_hash_utils.py
python ./common/test_maven_utils.py
python ./common/test_prompt_manager_factory.py
python ./common/test_send_email.py
python ./common/test_utils.py
python ./datasets/test_dataset.py
python ./datasets/test_hf_utils.py
python ./datasets/test_project.py
python ./eval/test_final_eval.py
python ./eval/test_repos.py
python ./lang/base/test_ast_parser_factory.py
python ./lang/base/test_builder_factory.py
python ./lang/base/test_builder.py
python ./lang/base/test_utils.py
python ./lang/java/maven/test_builder.py
python ./lang/java/maven/test_maven_utils.py
python ./lang/java/test_ast_parser.py
python ./lang/test_utils.py
python ./lm/test_grouped_llm_parser_factory.py
python ./lm/test_llm_agent_factory.py
python ./lm/test_llm_parser_factory.py
python ./lm/test_utils.py
python ./metrics/test_cloud_watch.py
python ./metrics/test_utils.py
